// Copyright 2000-2020 JetBrains s.r.o. and other contributors. Use of this source code is governed by the Apache 2.0 license that can be found in the LICENSE file.
{
  parserClass="com.github.nthykier.debpkg.deb822.parser.Deb822Parser"

  extends="com.intellij.extapi.psi.ASTWrapperPsiElement"

  psiClassPrefix="Deb822"
  psiImplClassSuffix="Impl"
  psiPackage="com.github.nthykier.debpkg.deb822.psi"
  psiImplPackage="com.github.nthykier.debpkg.deb822.psi.impl"
  psiImplUtilClass="com.github.nthykier.debpkg.deb822.psi.impl.Deb822PsiImplUtil"

  elementTypeHolderClass="com.github.nthykier.debpkg.deb822.psi.Deb822Types"
  elementTypeClass="com.github.nthykier.debpkg.deb822.psi.Deb822ElementType"
  tokenTypeClass="com.github.nthykier.debpkg.deb822.psi.Deb822TokenType"

  name("value_parts")="Value or Substvars"
}

deb822file ::= COMMENT* all_paragraphs COMMENT*

all_paragraphs ::= paragraph (COMMENT* paragraph)*
paragraph ::= field_value_pair (COMMENT* field_value_pair)* (PARAGRAPH_FINISH|<<eof>>) {
  extends="com.github.nthykier.debpkg.deb822.psi.impl.AbstractDeb822Paragraph"
  implements="com.github.nthykier.debpkg.deb822.psi.Deb822ParagraphSupport"
}


field_value_pair ::= field SEPARATOR value_parts {
  pin=2
/*  extends="com.github.nthykier.debpkg.deb822.psi.impl.Deb822FieldValueElementImpl"
  implements="com.github.nthykier.debpkg.deb822.psi.Deb822FieldValueElement"*/
  recoverWhile=recover_property
  //methods=[getFieldName getFieldValue getName setName getNameIdentifier getPresentation]
}

field ::= FIELD_NAME {
  methods=[getReference]
}
value_parts ::= COMMENT* (value|COMMA|substvar) (COMMENT|value|COMMA|substvar)*

value ::= VALUE_TOKEN {
  methods=[getReference]
}

substvar ::= SUBSTVAR_TOKEN {
  methods=[getReference]
}

private recover_property ::= !(FIELD_NAME|SEPARATOR|SUBSTVAR_TOKEN|VALUE_TOKEN|COMMA|COMMENT|PARAGRAPH_FINISH)
